project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - qmd/**/*.qmd  # recursively render all .qmd files
    
execute:
  freeze: auto
  
website:
  title: "Spatial Ecology - Shorebirds"
  
  navbar:
    background: primary
    search: true
    
    left:
      - text: "Project"
        href: qmd/teststart.qmd
        
      - sidebar:chapter1
      - sidebar:chapter2
      - sidebar:chapter3
      - sidebar:chapter4
      - sidebar:chapter5
      
      - text: "Acknowledgments"
        href: qmd/testend.qmd

  # Define multiple sidebars as a LIST
  sidebar:
    - id: chapter1
      title: "Chapter 1"
      style: docked
      background: light
      collapse-level: 2
      contents:
        - text: "Test 1"
          href: qmd/chapter_1/test1.qmd
        - section: "Test 2"
          contents:
            - qmd/chapter_1/test21.qmd
            - qmd/chapter_1/test22.qmd

    - id: chapter2
      title: "Chapter 2"
      style: docked
      background: light
      collapse-level: 2
      contents:
        - href: qmd/chapter_2/testch2.qmd

    - id: chapter3
      title: "Chapter 3"
      style: docked
      background: light
      collapse-level: 2
      contents:
        - href: qmd/chapter_3/testch3.qmd

    - id: chapter4
      title: "Chapter 4"
      style: docked
      background: light
      collapse-level: 2
      contents:
        - href: qmd/chapter_4/testch4.qmd

    - id: chapter5
      title: "Chapter 5"
      style: docked
      background: light
      collapse-level: 2
      contents:
        - href: qmd/chapter_5/testch5.qmd

format:
  html:
    theme: [cosmo, brand]
    css: styles.css
    toc: true

editor: visual